ユーザーのアクションをトリガーにリクエストを送る
tmosyc/kenshu-frontend-react pull request #2
Opened 2023-05-23 09:23 UTC by tmosyc

### 要件

- タスクを新しく作成するボタンが表示されていること
- このボタンをクリックするとタスクが新しく作成され、即座に一覧表示されているタスクに追加されること

### 補足

- API の仕様上、タスクの作成は body を含めずに単に POST するようになっていて、タイトルはデフォルト値です。そのため、作成はフォームではなくボタンのような UI で完結して問題ありません。

2023-05-23 09:58 UTC, szkyudi requested changes
「即座に追加される」という仕様を満たしていないですね。
ちなみに「即座に」というのはボタンを押した瞬間にリロードをせずともUIに反映されることを意味しています。

以下のリンクを参考に修正してみてください。
https://www.notion.so/React-051afd112f734095b3142da83999d481?pvs=4#a559a4072e1a4973af049f9d6046e53e

2023-05-24 05:35 UTC, szkyudi commented
まだ、前回のコメントの仕様を満たせていないですね。
`useMutation`の`onSuccess`などを使うと良いと思います。
https://tanstack.com/query/v4/docs/react/reference/useMutation

2023-05-25 01:27 UTC, szkyudi approved these changes
LGTMです！

↓次回からで大丈夫です！
コード内にコメントを残すのはいいことですが、コメントを残し過ぎても可読性が下がることがあるので、変数名を工夫するなどして、本当に必要なコメントのみ追記できるようになると良さそうです！

2023-05-25 01:27 UTC, szkyudi commented on app/src/App.tsx
>    const { data, isLoading, error } = useQuery({
こことかは `useQuery` からデータ取得をしていることは自明なので不要そうですね。

2023-05-25 01:27 UTC, szkyudi commented on app/src/App.tsx
> +  });
このコメントは、すでにあるコードに対するコメントとしては良さそうですが、`addToDoMutation` などとすれば、コメントを追加しなくても変数名のみで実装意図がわかるようになります。

2023-05-25 01:27 UTC, szkyudi commented on app/src/App.tsx
> +        </button>
ここのコメントについても `button` のテキストが「タスクの追加」となっているので、コメントがなくても実装意図を読み取ることができると思います。

2023-05-25 01:29 UTC, tmosyc commented on app/src/App.tsx
> +        </button>
承知しました！
ありがとうございます！

2023-05-25 03:06 UTC, merged